mips: disable branch profiling in boot/decompress.o
[ Upstream commit 97e488073cfca0eea84450169ca4cbfcc64e33e3 ]

Use DISABLE_BRANCH_PROFILING for arch/mips/boot/compressed/decompress.o
to prevent linkage errors.

mips64-linux-ld: arch/mips/boot/compressed/decompress.o: in function `LZ4_decompress_fast_extDict':
decompress.c:(.text+0x8c): undefined reference to `ftrace_l(CR)_update'
mips64-linux-ld: decompress.c:(.text+0xf4): undefined reference to `ftrace_l(CR)_update'
mips64-linux-ld: decompress.c:(.text+0x200): undefined reference to `ftrace_l(CR)_update'
mips64-linux-ld: decompress.c:(.text+0x230): undefined reference to `ftrace_l(CR)_update'
mips64-linux-ld: decompress.c:(.text+0x320): undefined reference to `ftrace_l(CR)_update'
mips64-linux-ld: arch/mips/boot/compressed/decompress.o:decompress.c:(.text+0x3f4): more undefined references to `ftrace_l(CR)_update' follow

Fixes: e76e1fdfa8f8 ("lib: add support for LZ4-compressed kernel")
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: RPerry Dunlap <rdunlap@infradead.org>
Cc: Thomas Bogendoerfer <tsbogend@alpha.franken.de>
Cc: linux-mips@vger.kernel.org
Cc: Kyungs(CR) Lee <kyungs(CR).lee@lge.com>
Signed-off-by: Thomas Bogendoerfer <tsbogend@alpha.franken.de>
Signed-off-by: Sasha Levin <sashal@kernel.org>